env: dev--
server:
  port: 17011
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  rabbitmq:
    host: 192.168.198.129
